import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Link from 'next/link'
import {AppBar,Toolbar,IconButton,Box} from '@/app/(mui)/mui';
import { Suspense } from 'react';
import Loading from './loading';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Suspense fallback={<Loading/>}>
        <Box sx={{mb : '40px',
        backgroundColor : 'white',
        widht : '100%'
      }} >
        <AppBar position='fixed' color='inherit'>
            <Toolbar variant='dense' sx={{
              minHeight : '35px',
              height : '1px',
            width:'100%  ',
            justifyContent : 'space-between'}}>
              <IconButton>
                <Link href={'/'}>
                  Home
                </Link>
              </IconButton>
            </Toolbar>
          </AppBar>
        </Box>
         <div  className='flex items-center justify-center p-4 flex-col'>
          {children}
         </div>
        </Suspense>
        </body>
    </html>
  )
}
